/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.OrderController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class HistoryPanel extends javax.swing.JPanel {

    private OrderController controller;
    private DefaultTableModel historyTableModel;
    
    public HistoryPanel(OrderController controller) {
        this.controller = controller;
        initComponents();
        setupComponents();
        loadHistory();
    }
    
    private void setupComponents() {
        // Setup Table Model
        String[] columns = {"Order ID", "Tanggal", "Total Item", "Total Harga", "Status"};
        historyTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableHistory.setModel(historyTableModel);
    }
    
    private void loadHistory() {
        historyTableModel.setRowCount(0);
        
        for (model.Order order : controller.getOrderHistory()) {
            Object[] row = {
                order.getOrderId(),
                order.getFormattedDate(),
                order.getItems().size(),
                String.format("Rp %.0f", order.getTotalPrice()),
                order.getStatus()
            };
            historyTableModel.addRow(row);
        }
        
        if (controller.getOrderHistory().isEmpty()) {
            txtDetail.setText("Belum ada history pesanan.");
        }
    }
    
    private void showOrderDetail() {
        int row = tableHistory.getSelectedRow();
        if (row == -1) return;
        
        model.Order order = controller.getOrderHistory().get(row);
        
        StringBuilder detail = new StringBuilder();
        detail.append("========================================\n");
        detail.append("Order ID: ").append(order.getOrderId()).append("\n");
        detail.append("Tanggal: ").append(order.getFormattedDate()).append("\n");
        detail.append("========================================\n\n");
        
        detail.append("Item Pesanan:\n");
        detail.append("----------------------------------------\n");
        
        for (model.OrderItem item : order.getItems()) {
            detail.append(String.format("%-20s x%d\n", 
                item.getMenuItem().getName(), 
                item.getQuantity()));
            detail.append(String.format("  @ Rp %.0f = Rp %.0f\n\n", 
                item.getMenuItem().getPrice(), 
                item.getSubtotal()));
        }
        
        detail.append("========================================\n");
        detail.append(String.format("TOTAL: Rp %.0f\n", order.getTotalPrice()));
        detail.append("========================================\n");
        
        txtDetail.setText(detail.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        txtDetail = new javax.swing.JLabel();

        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Tanggal", "Qty", "Total Harga", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableHistory);

        txtDetail.setText("RIWAYAT PEMESANAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(txtDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDetail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHistory;
    private javax.swing.JLabel txtDetail;
    // End of variables declaration//GEN-END:variables
}
