/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.OrderController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class HistoryPanel extends javax.swing.JPanel {

    private OrderController controller;
    private DefaultTableModel historyTableModel;
    
    public HistoryPanel(OrderController controller) {
        this.controller = controller;
        initComponents();
        setupComponents();
        loadHistory();
    }
    
    private void setupComponents() {
        // Setup Table Model
        String[] columns = {"Order ID", "Tanggal", "Total Item", "Total Harga", "Status"};
        historyTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableHistory.setModel(historyTableModel);
    }
    
    private void loadHistory() {
        historyTableModel.setRowCount(0);
        
        for (model.Order order : controller.getOrderHistory()) {
            Object[] row = {
                order.getOrderId(),
                order.getFormattedDate(),
                order.getItems().size(),
                String.format("Rp %.0f", order.getTotalPrice()),
                order.getStatus()
            };
            historyTableModel.addRow(row);
        }
        
        if (controller.getOrderHistory().isEmpty()) {
            txtDetail.setText("Belum ada history pesanan.");
        }
    }
    
    private void showOrderDetail() {
        int row = tableHistory.getSelectedRow();
        if (row == -1) return;
        
        model.Order order = controller.getOrderHistory().get(row);
        
        StringBuilder detail = new StringBuilder();
        detail.append("========================================\n");
        detail.append("Order ID: ").append(order.getOrderId()).append("\n");
        detail.append("Tanggal: ").append(order.getFormattedDate()).append("\n");
        detail.append("========================================\n\n");
        
        detail.append("Item Pesanan:\n");
        detail.append("----------------------------------------\n");
        
        for (model.OrderItem item : order.getItems()) {
            detail.append(String.format("%-20s x%d\n", 
                item.getMenuItem().getName(), 
                item.getQuantity()));
            detail.append(String.format("  @ Rp %.0f = Rp %.0f\n\n", 
                item.getMenuItem().getPrice(), 
                item.getSubtotal()));
        }
        
        detail.append("========================================\n");
        detail.append(String.format("TOTAL: Rp %.0f\n", order.getTotalPrice()));
        detail.append("========================================\n");
        
        txtDetail.setText(detail.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();

        setBackground(new java.awt.Color(147, 104, 58));

        jPanel1.setBackground(new java.awt.Color(147, 104, 58));

        txtDetail.setBackground(new java.awt.Color(147, 104, 58));
        txtDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDetail.setForeground(new java.awt.Color(255, 255, 255));
        txtDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDetail.setText("RIWAYAT PESANAN");

        tableHistory.setBackground(new java.awt.Color(247, 241, 222));
        tableHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Tanggal", "Qty", "Total Harga", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableHistory);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHistory;
    private javax.swing.JLabel txtDetail;
    // End of variables declaration//GEN-END:variables
}
